---
apiVersion: v2
name: zabbix
version: 0.2.2
appVersion: 5.0.4
description: Zabbix is a mature and effortless enterprise-class open source monitoring solution for network monitoring and application monitoring of millions of metrics.
keywords:
  - zabbix
  - monitoring
  - metics
home: https://www.zabbix.com/
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png
source:
  - https://github.com/cetic/helm-zabbix
maintainers:
  - name: AyadiAmen
    email: amen.ayadi@cetic.be
    url: https://github.com/AyadiAmen
  - name: alexnuttinck
    email: alexandre.nuttinck@cetic.be
    url: https://github.com/alexnuttinck
  - name: Aecio Pires
    email: aeciopires@gmail.com
    url: https://github.com/aeciopires
dependencies:
  - name: postgresql
    version: ~8.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
